name: new_gp_app
description: A simple starter Flutter app for team collaboration.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
